[package]
name = "shabby"
version = "0.1.0"
edition = "2024"
description = "A Telegram userbot for Sharparam"
repository = "https://github.com/Sharparam/shabby"
license = "MPL-2.0"
keywords = ["telegram", "userbot", "bot"]

[dependencies]
anyhow = "1.0.98"
grammers-client = "0.7.0"
tokio = { version = "1.45.1", features = ["full"] }
